### ISSUE TITLE
Ark-go config file, please add fourth payment possibility

### ISSUE THREAD

**Issue by Dr10tv** [kristjank/ark-go#20]
Hey guys,

first of all, thanks for your work. This payment script really looks cool! Hower I have a problem with with the ark-go config.toml, since there are three sections to pay the forged ARK to: voters, costs and reserve. I would need a fourth section for "private use". If I would send it this way:
voters 60
costs 10
reserve 20

I would have 90% only and cant execute the payment itself -> it crashes down without paying.

Now I added additional 10% to the costs to have 100%. But afterwards I need to manually send the 10% to my private account.

Hope I could clarify my situation and that you would add another possibilty (4th adress-section)

Thanks a lot! :)

**Comment by kristjank** [comment]
Jarnunik added a PR--- checking it and merging now
will send news :)

**Comment by kristjank** [comment]
implemeted
