### ISSUE TITLE
Please add: Don't send Profit share to excluded votes / Blacklisted

### ISSUE THREAD

**Issue by Dr10tv** [kristjank/ark-go#23]
After that I am ready to use your automated payment script! :)

**Comment by Jarunik** [comment]
As far as I understand the requirement is to ignore certain voter accounts completely. This means we would need a list of addresses in the config.toml file for all blacklisted transactions. When we calculate the vote share for each voter we should treat these accounts like they would have a balance of 0. Each other voter will get a higher share.

Looks like we need a new function in core to do that. Quick hack would be something like filtering out the accounts here: https://github.com/kristjank/ark-go/blob/master/core/delegate.go#L142 I guess chris should have a look how wants to include it.

**Comment by kristjank** [comment]
Implemented
