### ISSUE TITLE
Maximum Payout

### ISSUE THREAD

**Issue by Dr10tv** [kristjank/ark-go#38]
Hey Guys!

I'd like to request a "Maximum Payout" function for my Profit Share Payouts. 
Example:

I set Maximum Payout per week to 30 ARK. 
If someone votes with 50.000 ARK he gets 30 ARK from my calculation.
If someone votes with 10.000 ARK he also gets only 30 ARK.

I am looking to use this function, so that bigger voters only vote for me to really show support and  therefore smaller voters also have a more fairer distribution of the payouts. As I heard other Payout Scripts offer this, so I thought it might be possible to include it here too? :)

Thank you!

**Comment by kristjank** [comment]
Some major updates will be / and will also include this functionality... ETA not yet known...

**Comment by Jarunik** [comment]
I implemented automatic blacklisting of wallet above a certain cap.

Settings:
whitelist = "" #comma separated address list of addresses of voters to allow (despite capBalance)
capBalance = true #activate
balanceCapAmount = 20000.0 #amounts above this value are blacklisted

Example:
- capAmount: 20.0
- Voters Balance 19 -> normal payout
- Voters Balance 21 -> no payout at all

It is not exactly the same as the maximum payouts though.
Does the also solve your requirement @Dr10tv ?

**Comment by Jarunik** [comment]
I think we should just add a simple balance based cap which reduced the vote share to the cap balance.

Thus we have to add another configuration item:
- balanceCapBlock true/false

true -> block address completely
false -> reduce address vote weight to cap

Whitelist will also be apply and allow to specify addresses which should receive full payout.

It should be easy to implement.

**Comment by kristjank** [comment]
@Dr10tv please look at the #64 - would this solve your request. I think you get almoust the same functionaltiy - even better and more simple? 
Let me know

**Comment by Jarunik** [comment]
He said yes to me in chat

**Comment by kristjank** [comment]
Ok then we will close this one and do it the #64 way. Thanks

**Comment by Jarunik** [comment]
Implemented it. 

You can now use the option blockBalanceCap = false.

This will virtually reduce the balance of voters above cap down to the cap.

So profit shares will be as if they voted the cap.
