### ISSUE TITLE
Minimum Payout

### ISSUE THREAD

**Issue by reConNico** [kristjank/ark-go#48]
The script doesn't check the minimum Payout with following settings:

shareRatio = 0.85 #percent goes to voters
fidelity = true
fidelityLimit = 24  #fidelity limit in hours
minamount = 1.0 #minimum amount limit for payout.
deductTxFees = false #if true tx fees are deducted from recepients
blocklist = "" #comma separated address list of addresses of voters to block

**Comment by kristjank** [comment]
Hi m8,

looked at the code and it is fixed now. Was a conversion error... 
Now minumum amount works
