### ISSUE TITLE
Bug: GetVoteDuration

### ISSUE THREAD

**Issue by reConNico** [kristjank/ark-go#52]
The function GetVoteDuration checks all transactions and is searching for type == VOTE. When the function finds the first transaction with the type VOTE it return the hours.

The problem is: When someone is revoting the delegate the function still only get the first vote. 

> File: core/delegate.go
> Line: 194 - GetVoteDuration(address string)

We need to check the latest transaction of type == VOTE!

**Comment by kristjank** [comment]
Fixed
