### ISSUE TITLE
Performance Optimisation for Reward calculation

### ISSUE THREAD

**Issue by Jarunik** [kristjank/ark-go#62]
I think we should have a look if we can tune the reward calculation and make it faster.

For my 1000 voters it takes a bit too long. There must be some stuff we can optimise.

**Comment by kristjank** [comment]
Yeah Agreed - we should cache votes locally and check for new voters, periodically. As when calculation for every voter we check transactions - to get latest vote transaction - meaning 1000xREST API call.

Alternative we wait - and move this to goark-node when completed, or

**Comment by Jarunik** [comment]
I think it has no high priority right now. Maybe we wait for go node. Then we can directly access it in a fast way.

**Comment by kristjank** [comment]
agreed
