### ISSUE TITLE
Cap whales and distribute difference

### ISSUE THREAD

**Issue by galperins4** [kristjank/ark-go#64]
Is it possible to build functionality to have a cap on the payout up to a certain amount of votes. So for example, I set my cap at 50K and a voter has 100K. In this example, the voter would only be eligible for rewards based on 50K.

I would think this would be an easy if/else statement in the share calculation part of the code
if votes < cap:
     share = votes/total_pool_votes

else:
    share = cap/total_pool_votes

**Comment by kristjank** [comment]
is possible. Will look into it.

@Dr10tv - could this work for you?

**Comment by Jarunik** [comment]
I updated other cap and discussed with @dr10 it will work too. Wrote a solution outline in other issue Same as #38

**Comment by kristjank** [comment]
@Jarunik can we close this one - as now we added this functionality?

**Comment by Jarunik** [comment]
Yes. It is done.
