### ISSUE TITLE
TransactionConfirmationCheck

### ISSUE THREAD

**Issue by kristjank** [kristjank/ark-go#66]

**Comment by Jarunik** [comment]
Yes. We should check if the transactions that were sent to the network did get confirmations.

**Comment by alexbarnsley** [comment]
I've done this on the command line client. I'll take a look if I get chance. No experience with Go though. Do I merge into here or into the ArkEcosystem repo?

**Comment by kristjank** [comment]
hej - sorry didn't see the comment--- finishing this already as we speak... tnx @alexbarnsley...

**Comment by alexbarnsley** [comment]
No worries! A tonne of stuff came up since so completely forgot about it!
