### ISSUE TITLE
Incorrect vote hours displayed 

### ISSUE THREAD

**Issue by 0toierance** [kristjank/ark-go#73]
I received a vote from someone, and the script indicated that the voter has apparently been with me for 803Hrs. I have been running the node for maybe 3 days...very confusing.

**Comment by 0toierance** [comment]
https://arkecosystem.slack.com/messages/D7679JYJG/

**Comment by 0toierance** [comment]
https://gyazo.com/4f9c1c412f5cadcfe0d283796e448af5

**Comment by kristjank** [comment]
hi del, please attach your config or send it over to me in pm

**Comment by kristjank** [comment]
also please check if it is the same on linux. ty
