### ISSUE TITLE
Total amount of voters does not match how many are being paid. 

### ISSUE THREAD

**Issue by 0toierance** [kristjank/ark-go#74]
Currently I have 7 active voters who I must pay, but the script is indicating that there are only 6 in the second option of Send Payment. 

https://gyazo.com/8283419496b5a4d69d6505ed1f5c5828

**Comment by kristjank** [comment]
the missing voter is the one that just voted for you. You have fee deduction to true, meaning if the voter covers the fee - his payout amout is negative.... 

Let's say he earned 0.00223334 ARK - 0.1 fee = NEGATIVE PAYOUT... so he is not listed as he cannot receive the money...

To pay small voters set your fee deduction to false
